[project]
name = "ir-api"
readme = "README.md"
version = "0.0.1"
dependencies = [
    "fastapi[all]==0.104.0",
    "psycopg2==2.9.9",
    "SQLAlchemy==2.0.22",
    "pydantic==2.4.2",
    "uvicorn==0.23.2",
    "requests==2.31.0"
]

[project.urls]
"Repository" = "https://github.com/interactivereduction/ir-api"

[project.optional-dependencies]
formatting = [
    "black==23.9.1"
]

test = [
    "pytest==7.4.2",
    "requests==2.31.0",
    "httpx==0.25.0",
    "pytest-cov==4.1.0",
    "pytest-random-order==1.1.0",
    "Faker==19.13.0"

]

code-inspection = [
    "pylint==3.0.2",
    "mypy==1.6.1",
    "ir-api[test]",
    "types-requests==2.31.0.10",
    "types-urllib3==1.26.25.14"
]

dev = [
    "ir-api[code-inspection]",
    "ir-api[formatting]",
]


[tool.setuptools]
packages = ["ir_api"]