[project]
name = "ir-api"
readme = "README.md"
version = "0.0.1"
dependencies = [
    "fastapi[all]==0.100.0",
    "psycopg2==2.9.6",
    "SQLAlchemy==2.0.19",
    "pydantic==2.0.3",
    "uvicorn==0.22.0",
    "requests==2.31.0"
]

[project.urls]
"Repository" = "https://github.com/interactivereduction/ir-api"

[project.optional-dependencies]
formatting = [
    "black==23.3.0"
]

test = [
    "pytest==7.4.0",
    "requests==2.31.0",
    "httpx==0.24.1",
    "pytest-cov==4.1.0"
]

code-inspection = [
    "pylint==2.17.4",
    "mypy==1.4.1",
    "ir-api[test]",
    "types-requests==2.31.0.1",
    "types-urllib3==1.26.25.13"
]

dev = [
    "ir-api[code-inspection]",
    "ir-api[formatting]"
]


[tool.setuptools]
packages = ["ir_api"]