[project]
name = "ir-api"
readme = "README.md"
version = "0.0.1"
dependencies = [
    "fastapi[all]==0.95.1",
    "psycopg2==2.9.6",
    "SQLAlchemy==2.0.7",
    "pydantic==1.10.7",
    "uvicorn==0.21.1",
    "requests==2.28.2"
]

[project.urls]
"Repository" = "https://github.com/interactivereduction/ir-api"

[project.optional-dependencies]
formatting = [
    "black==23.3.0"
]

test = [
    "pytest==7.3.1",
    "requests==2.28.2",
    "httpx==0.23.3",
    "pytest-cov==4.0.0"
]

code-inspection = [
    "pylint==2.17.2",
    "mypy==1.2.0",
    "ir-api[test]",
    "types-requests==2.28.11.17",
    "types-urllib3==1.26.25.10"
]

dev = [
    "ir-api[code-inspection]",
    "ir-api[formatting]"
]


[tool.setuptools]
packages = ["ir_api"]